### ISSUE TITLE
Improve BBC Good Food image quality

### ISSUE THREAD

**Issue by petemill** [brave/news-aggregator#328]
The BBC Good Food feed items currently have poor image quality. In their feed the images have resize=150,150 param at the end, which we can add to our list of params to make better?

**Comment by LorenzoMinto** [comment]
This has been _somewhat_ fixed with the latest update
<img width="220" alt="Screenshot 2023-12-04 at 16 52 32" src="https://github.com/brave/news-aggregator/assets/13190144/88e88fe0-ff4c-455e-a932-6a34d4b38fd9">
We can do even better, but we should maybe do that on a next iteration. Can we close?

**Comment by aurangzaib048** [comment]
This issue is not for the cover image, but for article images. which is still not fixed

**Comment by LorenzoMinto** [comment]
Ops, my bad. Misread the description. All good

**Comment by LorenzoMinto** [comment]
General issue here https://github.com/brave/news-aggregator/issues/679
